### PR TITLE
Use ReadSeString for ReadStringFromPointer

### PR DESCRIPTION
**Pull request by aspiringnobody**
This is required because the game sometimes adds ~30 characters of junk to the castbar contents.  Seems to be used for formatting (bold/italics/color/whatever), mostly for on-use items (like learning a mount from an item).

Since we don't use the game's formatting for anything we need to filter this out.  I let VSCode pre-bake this in my earlier code but I left it inline here -- I figured you can pre-bake it if you want to, not sure if it really will make any performance difference or not.

But TL,DR: we actually need this RegEx if we are going to use the castbar contents.  If you don't want to have to use a regular expression I suggest we revert to using GetAbilityName() instead.

### CODE REVIEW

**Comment by aspiringnobody** [comment]
If you have a Vesper Bay Aetheryte Ticket in your inventory you can use that to reproduce easily.

**Comment by aspiringnobody** [comment]
Tested and I don't see a performance benefit on either of my machines (5800X3D or 14700k) so for what it's worth I don't think pre-baking has any benefit.

**Comment by CaiClone** [comment]
Thanks for the report!
I see, the castbar text is an sestring. I was wondering when implementing this but I wasn't able to find any example so I thought it could have been a normal string.
Replacing the `Marshal.PtrToStringUTF8(new nint(*ptr))` in `ReadStringFromPointer` with `MemoryHelper.ReadSeStringNullTerminated(new nint(*ptr)).TextValue;` should solve this and be resilient for the future. Can you try that approach and see if it works for your use cases?

**Comment by aspiringnobody** [comment]
That works.  I updated the PR.  I also removed another unneeded config setting: HideAnimationLock.  It wasn't included in the BarDecisionHelper when I refactored it, so it wasn't doing anything anyway.  I started to re-implement it but it's surprisingly involved (TL,DR: you'd need to make HandleGCDOnly aware of the bar state and behave differently if LongCast OR include all the functionality of HandleGCDOnly inside HandleCastBarLong. Otherwise if you have slidecast off, the queuelock option wouldn't work).

I didn't feel like making HandleGCDOnly have all that extra complexity so I just axed it altogether.

**Comment by CaiClone** [comment]
Looks perfect! I did saw that option as a candidate for removal, so knowing it wasn't fully implemented makes a lot of sense. Agree on both changes and merging.

**Pull request merged**
